---
- name: Uninstall Java, Python, Notepad++, Tomcat, and Ubuntu Desktop
  hosts: all
  become: yes
  tasks:
    - name: Remove Java
      apt:
        name: default-jdk
        state: absent
      tags: 
        - java

    - name: Remove Python
      apt:
        name: python3
        state: absent
      tags: 
        - python
